name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 23

      - name: Enable PNPM
        run: corepack enable

      - name: Install Node.js dependencies
        run: pnpm i

      - name: Build app
        run: pnpm run build --base https://trentindustries.github.io/carrier-trade-calculator/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
